### ISSUE TITLE
Notification knowledge collected

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#115]
What about considering the possibility of customized notification functionality after e.g. the knowledge collection is done?

We can make it by sending mail for example.

**Comment by pacospace** [comment]
What is the use case here? :) 

The knowledge collection is 'never' done I would say because we continuously learn from repositories.

**Comment by xtuchyna** [comment]
> What is the use case here? :)

The use case is for someone that uses cronjob for knowledge collection. The user would know how well or how much new knowledge had been collected.

Or is it more a SLI/SLO thing rather than a functionality provided by srcops?

**Comment by xtuchyna** [comment]
aight, will take it as a unnecessary feature for now and therefore close this one
