### ISSUE TITLE
Argo workflow collecting, processing and storing knowledge on Ceph [8pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/mi#132]
I want to create an Argo workflow collecting, processing and storing knowledge on Ceph,
so that the final visualized report does not have to create its own knowledge everytime it is accessed. 

Acceptance Criteria

- [x] create WorkflowTemplate for srcopsmetrics with steps: collecting, processing and store everything on Ceph using srcopsmetrics CLI directly in the task

- [x] create Openshift Template with Worfklow that referenced the template created above

- [ ] add env variable to decide where to store the output of SrcOpsMetrics

- [x] create a method in Thoth-common Workflow Class to schedule that workflow using the Openshift template (https://github.com/orgs/thoth-station/projects/13#card-39843294)

- [x] create a method in `thoth-common` Openshift Class that calls the method in the Workflow class. (https://github.com/orgs/thoth-station/projects/13#card-39843294)

- [ ] ~~modify `srcopsmetrics CLI` using the method in Openshift class to have a command that is able to schedule workflow for one repository or organization.~~

- [x] make new project that schedules workflows using methods in common

- [x] store a CM with registered projects

**Comment by xtuchyna** [comment]
This Issue was completed within the PR #168 
Closing the issue.
