### ISSUE TITLE
Use Argo to store knowledge on ceph

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#133]
Instead of using the srcopsmetrics ceph knowledge storing, make Argo store the knowledge.

**Comment by fridex** [comment]
@xtuchyna is this still relevant?

**Comment by xtuchyna** [comment]
@fridex this is in question. Having argo storing the knowledge, we could exclude the ceph storing functionality from mi - however the ceph loading would still remain (knowledge updating & processing)

**Comment by goern** [comment]
@xtuchyna is this still a thing we want to do?

**Comment by xtuchyna** [comment]
@goern I would say so. If we could store the data by using Argo, the whole ceph handling could be removed from `mi`, which would result in better structured application. The `mi` would in the end only care about storing data wherever it is running - a lot of code could be possibly removed (e.g. cluttered presence of `is_local` parameter) and it would be more clear, more readable.

Also, a lot of unnecessary parameters could be removed as well (see https://github.com/thoth-station/thoth-application/blob/8f7b0eb6bbc9a759172153f9edb864fc0bebf957/mi-scheduler/base/argo-workflows/mi-workflow-template.yaml#L75 - all ceph related parameters).

I would say that maybe /kind important-longterm suits this best?
