### ISSUE TITLE
Add Release as an entity that would be inspected and stored 

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#134]
As SrcOpsMetrics user,

I would like to have info about releases of a project so that I can analyze the behaviour after all release.

**Comment by xtuchyna** [comment]
Can be valuable to checkout [this](https://docs.google.com/document/d/110qgNKiRE9i5L7ruVMWjIuflx2YAQPZV9A6Qb61uYW8/edit) and approach @fridex and @tushar7sharma

**Comment by fridex** [comment]
It might be a good idea to check how other communities (e.g. openstack, project gnu, ...) store information about releases (how they structure it). If some automatic (machine) parsing can be subsequently used for our releases, it would be great for any further analyses.

CC @tushar7sharma
