### ISSUE TITLE
Entity classes (code refactor)

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#138]
**Is your feature request related to a problem? Please describe.**
Currently, for a valid implemented entity that will be analysed, contributor needs to meet several criteria on where to include the entity's implementation described in the main `README` file. This includes several issues with the code:

1. entity implementation becomes kind of parted on different places in project, in means of not having just one class for one entity (where all of the implementation would be stored), and therefore it becomes quite chaotic and not simple to implement

2. it also seems that currently, every entity has a same concept of method implementation. function `analyse_<entity>` is called and within the `store_<entity>` is called

**Describe the solution you'd like**
I suggest having a standalone directory `entities` which would include an `Entity` class that would represent a parent from which each entity should inherit. This will be a kind of schema that every new entity should respect in order for SrcOpsMetrics to collect it.

By implementing a base class for all of the entities, the code duplication of `analyse_` and `store_` methods described in 2. can be avoided and contributor can focus only on actual implementation.

**Additional context**
This code refactor will be in my opinion beneficial both for new contributors and the future of the code health of SrcOpsMetrics project.

**Comment by xtuchyna** [comment]
@pacospace @goern @fridex what are your opinions about this?

**Comment by fridex** [comment]
I don't have deeper understanding of the source code present in this repo, but the approach you've described sounds correct to me.

You can check thoth-storages repo and `ResultStorageBase` class that needs to be inherited for any result specific adapter, e.g. [for cloc results](https://github.com/thoth-station/storages/blob/master/thoth/storages/si_cloc.py). I think it follows your description, this way you are reusing code logic and making the code more maintainable (following OOP paradigm).
