### ISSUE TITLE
Deletion of Dash visualizations

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#176]
Should we remove the currently unused dash visualizations?

First mentioned in discussion here: #168 (comment)

My opinion is yes due to the fact that you can also run superset locally - therefore we could somehow keep default configuration from Superset (if it is possible) and leave it in here (public repo) for other interested people to use locally.

**Comment by goern** [comment]
+1 lets remove code that is not used #generalStatement

/assign @xtuchyna
