### ISSUE TITLE
Label bot dataset

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#278]
**Is your feature request related to a problem? Please describe.**
Having a label bot inside our organization (see https://github.com/thoth-station/kebechet/issues/586) requires training it on Issue / PR dataset consisting of stored labels.

**Describe the solution you'd like**
1. Original label bot https://github.com/machine-learning-apps/Issue-Label-Bot
2. Giorgos version https://github.com/GiorgosKarantonis/Github-Issues-Classifier 

**Acceptance criteria**

- [ ]  Look at the datasets used in 1. and 2. 

- [ ]  Consider what can be improved in means of simplicity or better accuracy

- [ ]  Implement #173  or consider it invalid if it does not imporve the quality of dataset

- [ ] Study used models above. Use the one from Giorgos if sufficient

- [ ] Integrate the bot as a new Kebechet Manager

**Additional context**

**Comment by xtuchyna** [comment]
I don't think this should be part of `mi`, but rather a `glyph` submodule.
cc @goern @pacospace ?

**Comment by pacospace** [comment]
@goern someone from aiops team is also looking at this right?

**Comment by goern** [comment]
/remove-lifecycle rotten
/triage needs-information

@durandom could you point us at the right person?

**Comment by goern** [comment]
It might be good to move this issue to https://github.com/aicoe-aiops/github-labeler

**Comment by goern** [comment]
@xtuchyna ping

**Comment by xtuchyna** [comment]
@goern I think that this may be closed. Issue was referenced in new issue under `github-labeler` repo, so there's no need to keep it alive here. Closing
