### ISSUE TITLE
aggregate new metric "Pull Requests Discussions"

### ISSUE THREAD

**Issue by goern** [thoth-station/mi#301]
**Is your feature request related to a problem? Please describe.**
Aggregating a "PR discussion" metric will help us figure out if noisy discussion of a PR will lead to slowing down its time-to-merge. Also, a sentiment of the discussion might be a valuable indicator. Including the role (reviewer, commiter, other, .. ) of the participants in the discussion might be interesting.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by xtuchyna** [comment]
Ay, didn't notice this was not closed.
