### ISSUE TITLE
Entity tests

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#326]
**Is your feature request related to a problem? Please describe.**
Everytime a PR is being made, we currently don't have any tests for Entity logic - meaning if there is something wrong (and contributor forgets to test) the failure occurs on openshift in scheduled workflow, which takes a lot of developer's time to look for the error and fix it (making another PR, requesting another review, etc.) 

**Describe the solution you'd like**
Having tests for every entity against (let's say) "fake" repository (which will contain preconstructed information, the goal would be only to test entities implemented in `mi`). 

**Additional context**
Open for discussion, @thoth-station/devops

**Comment by xtuchyna** [comment]
Use `hypothesis` package for entity data testing #370

**Comment by xtuchyna** [comment]
Sorry for my memory, but what was the test repository (I think we have one on GH) you suggested for using in tests @goern ?

**Comment by codificat** [comment]
Removing inconsistent (duplicate and conflicting) labels, leaving the latest that were added:

/remove-priority backlog
/remove-kind question
