### ISSUE TITLE
Create Data aggregation request Issue template

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#410]
SSIA

**Is your feature request related to a problem? Please describe.**
Related to https://github.com/thoth-station/mi/#data-extraction-request

**Comment by goern** [comment]
@xtuchyna is this valid?

/triage needs-information
/kind feature
/kind demo

**Comment by xtuchyna** [comment]
geeee, this is already in the mi :see_no_evil: Forgot to close
It is however not available, I think that someone with privileges has to set it up in the UI to be the template.

**Comment by xtuchyna** [comment]
Aight, new issue in `mi-scheduler` created for his, therefore I am closing it here :partying_face:
