### ISSUE TITLE
Can MI Project also get Github Traffic related info from repos?

### ISSUE THREAD

**Issue by oindrillac** [thoth-station/mi#451]
For https://github.com/aicoe-aiops/ocp-ci-analysis/issues/382, we need to extract [traffic related information](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-traffic-to-a-repository) for the [ocp-ci](https://github.com/aicoe-aiops/ocp-ci-analysis) repository. We need to extract and store them on a recurring basis as traffic info only persists on github for 14 days by default. Does MI enable this?

**Comment by xtuchyna** [comment]
Yes, mi can do that for you. Lemme create a PR for you to give you data example
Maybe you would be interested in `Events`  https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types too

**Comment by xtuchyna** [comment]
Btw @oindrillac I would need GH token from your side that is going to have push access to `ocp-ci-analysis`.
Traffic information cannot be accessed without it

**Comment by oindrillac** [comment]
> Btw @oindrillac I would need GH token from your side that is going to have push access to `ocp-ci-analysis` repository.
> Traffic information cannot be accessed without it

thanks for setting this up for us @xtuchyna. what kind of a token do you need? Is it a personal access token? or can we use deploy keys? https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys

cc: @michaelclifford

**Comment by oindrillac** [comment]
> Maybe you would be interested in `Events` https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types too

Yes, Events seem valuable to us. We are definitely interested in Forks and Stars which I think Events will capture.

**Comment by oindrillac** [comment]
cc: @hemaveeradhi @aakankshaduggal

**Comment by xtuchyna** [comment]
> > Btw @oindrillac I would need GH token from your side that is going to have push access to `ocp-ci-analysis` repository.
> > Traffic information cannot be accessed without it
> 
> thanks for setting this up for us @xtuchyna. what kind of a token do you need? Is it a personal access token? or can we use deploy keys? https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys
> 
> cc: @MichaelClifford

Personal access token

**Comment by MichaelClifford** [comment]
@xtuchyna 

1) Do any of the bots have existing access tokens that can be used? for example Sesheta?
2)  If not, how would you like us to share the access token?  
3) We could also make you a member of the project repo if that would be easier

WDYT?

**Comment by oindrillac** [comment]
cc'ing @harshad16 since there was some discussion on personal access tokens, deploy keys here https://github.com/aicoe-aiops/vulnerability-analysis/issues/62

**Comment by aakankshaduggal** [comment]
@xtuchyna 

**Collecting GitHub Traffic Data** 

We have tried out https://github.com/gomesfernanda/some-github-metrics.git for collecting some metrics for the existing data(past 14 days) 
As of now, we have the following metric data for all `aicoe-aiops` repositories :
* Git clones per day and unique git clone per day
* Code frequency - Weekly additions, deletions, commits, author, is-a member
* Community Engagement - Total number of forks, stars, commits, and collaborators
* Views per day and unique views per day

Is it possible to collect the above mentioned metrics using MI? The repository mentioned above has the scripts to collect these metrics as well.

cc - @MichaelClifford

**Comment by xtuchyna** [comment]
Hello ppl, data is ready to be updated daily on your cluster.
Please, have a look at
```
aws s3 --profile rick ls s3://opf-datacatalog-zero-backup/mi/srcopsmetrics/bot_knowledge/aicoe-aiops/ocp-ci-analysis/
```

**Comment by pacospace** [comment]
> ja, we have a s3 bucket for this on op1st
> 
> @pacospace

public bucket in Operate First is documented here: https://github.com/operate-first/apps/pull/1273/files, remember that the size of that bucket is fixed
