### ISSUE TITLE
Can we fetch all GitHub repos information using MI scheduler

### ISSUE THREAD

**Issue by hemajv** [thoth-station/mi#477]
As part of Project San Diego, we are trying to figure out what tool would be best suited to fetch and generate a list of all GitHub open source projects via the license file and other license related distinctions.
(_Related issue_: https://github.com/sandiego-rh/sandiego/issues/80)

One of the options we were considering was to use [GraphQL](https://docs.github.com/en/graphql) and were interested to know if this is something the MI scheduler uses and can help with.

cc @cdolfi @xtuchyna

**Comment by hemajv** [comment]
For example, GraphQL has a `licenses` query which returns a list of all open source licenses: https://docs.github.com/en/graphql/reference/queries#license, and we are interested to see if we can use this to fetch the associated repo names as well

**Comment by xtuchyna** [comment]
Status:

I have found out that Search API only provides searching for the first `1,000` results, which is limitating for the original goal of the Issue (that is to extract all of the repos given licenses).

Therefore, the Search API does not solve the problem, and we have to look into other possibilities (GraphQL, BigQuery, and there is also https://sourcegraph.com/ )
