### ISSUE TITLE
Unable to collect Issues from repository

### ISSUE THREAD

**Issue by oindrillac** [thoth-station/mi#504]
**Describe the bug**
Unable to collect Issues from repository. 

**To Reproduce**
1. Setup personal access token as env variable
2. Run `python -m srcopsmetrics.cli --create-knowledge --is-local --repository openshift/origin --entities Issue`
3. See error

```
oindrillachatterjee@Oindrillas-MBP mi % python -m srcopsmetrics.cli --create-knowledge --is-local --repository openshift/origin --entities Issue
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.bot_knowledge:######################## Analysing openshift/origin ########################

INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Detected entities:
CodeFrequency # Commit # DependencyUpdate # Fork # Issue # IssueEvent # KebechetUpdateManager # License # PullRequest # PullRequestDiscussion # ReadMe # Release # Stargazer # TrafficClones # TrafficPaths # TrafficPaths # TrafficReferrers # TrafficClones # TrafficViews
INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Issue inspection
INFO:srcopsmetrics.entities.tools.storage:Loading knowledge locally
INFO:srcopsmetrics.entities.tools.storage:Data from file %s loaded
INFO:srcopsmetrics.entities.interface:No previous knowledge of type Issue found
INFO:srcopsmetrics.iterator:-------------Issue Analysis-------------
WARNING:srcopsmetrics.iterator:403 {"message": "API rate limit exceeded for user ID 32435206.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
WARNING:srcopsmetrics.iterator:Problem occured, cached data will be saved
INFO:srcopsmetrics.iterator:Nothing to store, no update operation needed
INFO:srcopsmetrics.bot_knowledge:

```
**Expected behavior**
Should fetch Issues for openshift/origin repo

cc: @chauhankaranraj

**Comment by xtuchyna** [comment]
Hello @oindrillac, thanks for feedback!

`GITHUB_ACCESS_TOKEN` must be specified as an environment variable. This was somehow lost in documentation as I see now...

**Comment by chauhankaranraj** [comment]
> `GITHUB_ACCESS_TOKEN` must be specified as an environment variable, with generated access token (has limit of 5,000 requests).

Thanks @xtuchyna, so actually we were able to figure that bit out, and we set the `GITHUB_ACCESS_TOKEN` env var to our github personal access token. With this, we were able to get PullRequest data (first screenshot), but not Issues data (second screenshot).

![Screenshot from 2022-02-02 18-23-00](https://user-images.githubusercontent.com/15005500/152188677-98387cf4-77cd-4063-8acc-41c30b0a8d3e.png)

![Screenshot from 2022-02-02 19-49-24](https://user-images.githubusercontent.com/15005500/152188825-7db9e41b-45cc-4357-af5d-5ea0160ef149.png)

Any ideas what we might be missing here?

note: i stopped the first command after a few seconds, so that the github api rate limit is not exhausted by the time i start running the second command.

**Comment by xtuchyna** [comment]
@chauhankaranraj what version of `mi` are you using?
also, do you use the token for anything else, or is it your private personal token?

**Comment by oindrillac** [comment]
@xtuchyna I was running this on the `2.0.1` version of srcopsmetrics. 

Also I was using a personal access token that I had created  just for this use case.

**Comment by xtuchyna** [comment]
> @xtuchyna I was running this on the `2.0.1` version of srcopsmetrics.
> 
> Also I was using a personal access token that I had created just for this use case.

Hey @oindrillac, please update `mi` to the newest version `2.10.2`, the `2.0.1` is nearly two years old and there can be a lot of issues

**Comment by oindrillac** [comment]
Updated srcopsmetrics to `2.10.2` and I get the same error with both `PullRequest` and `Issue` entity

```
$ python -m srcopsmetrics.cli --create-knowledge --is-local --repository openshift/origin --entities Issue      
INFO:srcopsmetrics.github_knowledge:Overall repositories found: 1
INFO:srcopsmetrics.bot_knowledge:######################## Analysing openshift/origin ########################

INFO:srcopsmetrics.bot_knowledge:########################
INFO:srcopsmetrics.bot_knowledge:Detected entities:
INFO:srcopsmetrics.bot_knowledge:########################
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/srcopsmetrics/cli.py", line 215, in <module>
    cli(auto_envvar_prefix="MI")
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/srcopsmetrics/cli.py", line 178, in cli
    analyse_projects(repositories=repos, is_local=is_local, entities=entities_args)
  File "/usr/local/lib/python3.9/site-packages/srcopsmetrics/bot_knowledge.py", line 83, in analyse_projects
    raise NotKnownEntitiesError(
srcopsmetrics.exceptions.NotKnownEntitiesError: ('Invalid specified entities: %s', ['Issue'])
```
@chauhankaranraj do you see the same log on this version of srcopsmetrics?

**Comment by xtuchyna** [comment]
Patch is on the way, just waiting it to be delivered onto PyPI https://github.com/thoth-station/mi/issues/520

**Comment by oindrillac** [comment]
thanks @xtuchyna

**Comment by xtuchyna** [comment]
Okay @oindrillac , patch delivered (sadly we experienced some minor deployment issues that delayed it)
please update to `2.10.4` and let me know if the issue persists

**Comment by oindrillac** [comment]
Just wanted to update here, that fetching the issues seems to be working for smaller repos. I was able to download issues for the `open-services-group/metrics` repo. So this above issue on the `openshift/origin` repository seems something to do with the large size of the repository

![image](https://user-images.githubusercontent.com/32435206/154327914-f4537fc8-ef84-4378-82e2-022d5a3be7a7.png)

**Comment by xtuchyna** [comment]
Hey @oindrillac , sorry for stale issue. This should be fixed by https://github.com/thoth-station/mi/pull/547
Also, there's new entity called `RawIssue` and `RawPullRequest` that can be tried (it is basically a non-restrictive data aggregation of such entities)

**Comment by xtuchyna** [comment]
Hello @oindrillac , did the patch work?
