### ISSUE TITLE
Deliver Missing Module

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/mi#520]
Hey, AICoE-CI!

Please deliver the package module for the following tag, as it missing on PyPI:

Tag: v2.10.3

**Comment by harshad16** [comment]
This line seems to be the culprit 
https://github.com/thoth-station/mi/blob/854e6292131cda7b635e40daa50ee88bdface94a/setup.py#L62

seems like rendering the utf-8 might be causing issue
https://github.com/thoth-station/mi/blob/854e6292131cda7b635e40daa50ee88bdface94a/setup.py#L54
