### ISSUE TITLE
Schedule and fetch Github data for OSG org and other repos

### ISSUE THREAD

**Issue by hemajv** [thoth-station/mi#530]
We would like to use the MI scheduler to schedule daily collection of GitHub data for the OSG org as well as other sub-project repos under different SIGs mentioned in https://github.com/open-services-group/community/blob/main/sigs.yaml and have them stored, to start tracking and capturing metrics.

Related to https://github.com/open-services-group/metrics/issues/13

The data we would like:

- [ ] Issues
- [ ] PRs

cc @Shreyanand @MichaelClifford @xtuchyna

**Comment by xtuchyna** [comment]
Hello @hemajv , is this still relevant?
