### ISSUE TITLE
Unable to load github data locally

### ISSUE THREAD

**Issue by hemajv** [thoth-station/mi#539]
We tried to use the MI module within jupyter notebooks to fetch/load the GitHub data locally, but we ran into some issues:

### Steps to Reproduce
1. Go to Smaug JH instance or JH notebook from your local machine
2. Import latest `srcopsmetrics` package, `v2.10.4`
3. Import `entities.PullRequest` to load PR data

![Screenshot from 2022-02-24 12-28-59](https://user-images.githubusercontent.com/7343099/155576302-7eeaf1bb-74fa-4050-82de-f42643bb0e45.png)

We also had another issue where it was asking to specify the Thoth Ceph buckets when setting `is_local=True`

cc @xtuchyna @Shreyanand @chauhankaranraj

**Comment by xtuchyna** [comment]
Hello @hemajv , please try the patched `v2.10.5`

**Comment by hemajv** [comment]
@xtuchyna the issue now seems to be resolved :tada: Thanks for fixing this quickly!

**Comment by xtuchyna** [comment]
thanks @hemajv , feel free to close the issue :)
